### ISSUE TITLE
Move the class definition to simple Object literals

### ISSUE THREAD

**Issue by duranmla** [debtcollective/document-service#24]
Currently, we are using a definition of document types throughout classes without any meaningful propose, besides, it makes us export an instance of that class. Instead, we can define object literals and the type for it within the flow-typed to keep the consistent interface. Having that in place will avoid us to use constructors for side effects.

**Comment by orlando** [comment]
We do need this for inheritance. We can do the same with objects, but we will need to extend the object with the `Document` class, so is going to be pretty much the same.

I'll close this for now
